version: "3.3"
services:
  redis:
    image: redis:3-alpine
    command: redis-server --appendonly yes
    networks:
      - web
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data

networks:
  web:

volumes:
  redis_cache:
